"""Web Font 字體反爬蟲解密模組。

負責解析與還原提莫書屋 (timotxt.com) 等網站透過自定義字型混淆的韓文字元與 Unicode 偽裝。
"""

import re
from typing import Dict

# 提莫書屋 (timotxt.com) 混淆字符 149 字完整還原對照表
TIMOTXT_FONT_MAP: Dict[str, str] = {
    "\uAD17": "二",
    "\uAD5B": "十",
    "\uAD5C": "丁",
    "\uAD9D": "七",
    "\uADF7": "八",
    "\uADF8": "人",
    "\uADF9": "入",
    "\uAE47": "九",
    "\uAE4A": "了",
    "\uAE85": "刀",
    "\uAE86": "力",
    "\uAE97": "又",
    "\uAE98": "三",
    "\uAE9B": "干",
    "\uAEB1": "土",
    "\uAEB2": "工",
    "\uAEB3": "才",
    "\uAEB4": "寸",
    "\uAEB5": "丈",
    "\uAEB6": "大",
    "\uAED7": "上",
    "\uAED8": "小",
    "\uAED9": "口",
    "\uAEDA": "山",
    "\uAEDB": "巾",
    "\uAEDC": "千",
    "\uAEE1": "亡",
    "\uAEE3": "之",
    "\uAEE5": "已",
    "\uAEE6": "弓",
    "\uAEE7": "己",
    "\uAEE9": "也",
    "\uAF06": "乞",
    "\uAF07": "川",
    "\uAF0A": "麼",
    "\uAF0B": "久",
    "\uAF0C": "勺",
    "\uAF0D": "丸",
    "\uAF0E": "凡",
    "\uAF10": "及",
    "\uAF57": "叉",
    "\uAF6C": "夫",
    "\uAF6D": "天",
    "\uAF6E": "元",
    "\uAF71": "扎",
    "\uAF89": "五",
    "\uAF8A": "支",
    "\uAFA6": "犬",
    "\uAFA8": "尤",
    "\uAFA9": "匹",
    "\uAFAB": "巨",
    "\uAFAC": "牙",
    "\uAFAD": "屯",
    "\uAFAE": "互",
    "\uAFBF": "切",
    "\uAFC0": "止",
    "\uAFC1": "少",
    "\uAFC2": "日",
    "\uAFD7": "中",
    "\uAFDB": "手",
    "\uAFE2": "午",
    "\uAFE4": "升",
    "\uAFE6": "仁",
    "\uAFE7": "片",
    "\uAFE8": "化",
    "\uAFE9": "仇",
    "\uAFEB": "仍",
    "\uAFED": "斤",
    "\uAFEE": "爪",
    "\uAFEF": "反",
    "\uAFF0": "介",
    "\uAFF5": "父",
    "\uAFF7": "今",
    "\uAFF8": "凶",
    "\uAFF9": "乏",
    "\uAFFB": "氏",
    "\uB010": "欠",
    "\uB011": "丹",
    "\uB014": "勾",
    "\uB016": "六",
    "\uB017": "文",
    "\uB018": "方",
    "\uB019": "火",
    "\uB01E": "心",
    "\uB01F": "尺",
    "\uB027": "巴",
    "\uB02A": "以",
    "\uB02B": "允",
    "\uB02C": "予",
    "\uB0EA": "幻",
    "\uB0EB": "玉",
    "\uB0EC": "末",
    "\uB0ED": "未",
    "\uB148": "打",
    "\uB149": "巧",
    "\uB14A": "正",
    "\uB14C": "功",
    "\uB14D": "扔",
    "\uB160": "甘",
    "\uB161": "世",
    "\uB162": "古",
    "\uB164": "本",
    "\uB166": "可",
    "\uB167": "去",
    "\uB168": "左",
    "\uB16A": "石",
    "\uB17F": "右",
    "\uB180": "布",
    "\uB182": "平",
    "\uB185": "的",
    "\uB186": "是",
    "\uB187": "在",
    "\uB18A": "不",
    "\uB18B": "有",
    "\uB18C": "和",
    "\uB196": "我",
    "\uB198": "由",
    "\uB199": "只",
    "\uB19A": "要",
    "\uB19B": "他",
    "\uB1FD": "叫",
    "\uB1FE": "用",
    "\uB201": "四",
    "\uB202": "失",
    "\uB203": "生",
    "\uB204": "到",
    "\uB211": "代",
    "\uB212": "作",
    "\uB213": "地",
    "\uB215": "出",
    "\uB280": "就",
    "\uB281": "分",
    "\uB282": "乎",
    "\uB284": "令",
    "\uB285": "成",
    "\uB289": "句",
    "\uB28C": "外",
    "\uB2B3": "冬",
    "\uB2B5": "包",
    "\uB37F": "主",
    "\uB380": "市",
    "\uB383": "年",
    "\uB3D7": "它",
    "\uB561": "百",
    "\uB562": "同",
    "\uB563": "能",
    "\uB564": "而",
    "\uB598": "下",
    "\uB59A": "子",
}


def decode_timotxt_text(text: str) -> str:
    """將含有 timotxt 自定義字體混淆的字串還原為正確繁體中文字。

    Args:
        text: 混淆字串。

    Returns:
        還原後的純淨繁體中文字串。
    """
    if not text:
        return text

    # 使用字典逐字替換
    chars = [TIMOTXT_FONT_MAP.get(ch, ch) for ch in text]
    return "".join(chars)
